packages:
  - "odavl-studio/insight/*"
  - "odavl-studio/autopilot/*"
  - "odavl-studio/guardian/*"
  - "apps/*"
  - "packages/*"
  - "packages/plugins/*"
  - "tools/*"
  - "internal/*"
  - "github-actions"
