#!/usr/bin/env pwsh
# ODAVL Pilot - After Evidence Collection  
# Collects metrics after ODAVL improvements and generates delta analysis

param(
    [Parameter(HelpMessage="Output directory for after reports")]
    [string]$OutputDir = "reports/phase5/evidence/after",
    [Parameter(HelpMessage="Baseline directory for comparison")]
    [string]$BaselineDir = "reports/phase5/evidence/baseline", 
    [Parameter(HelpMessage="Output JSON format for automation")]
    [switch]$Json
)

$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ"
$projectRoot = (Get-Location).Path

Write-Host "📈 ODAVL After Evidence Collection - $timestamp" -ForegroundColor Cyan

# Ensure output directory exists
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# Load baseline for comparison
$baseline = $null
if (Test-Path "$BaselineDir/baseline-complete.json") {
    try {
        $baseline = Get-Content "$BaselineDir/baseline-complete.json" -Raw | ConvertFrom-Json
        Write-Host "📋 Loaded baseline from $BaselineDir" -ForegroundColor Gray
    } catch {
        Write-Host "⚠️ Could not load baseline data: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

# Collect current metrics (reuse baseline collection logic)
Write-Host "🔍 Collecting current metrics..." -ForegroundColor Yellow

# Run the baseline collection script to get current state
$currentResults = & "$PSScriptRoot/collect-baseline.ps1" -OutputDir $OutputDir -Json | ConvertFrom-Json

# Calculate deltas if baseline exists
$deltas = @{}
if ($baseline) {
    $deltas = @{
        eslintWarnings = ($currentResults.summary.eslintWarnings) - ($baseline.summary.eslintWarnings)
        eslintErrors = ($currentResults.summary.eslintErrors) - ($baseline.summary.eslintErrors)  
        typeErrors = ($currentResults.summary.typeErrors) - ($baseline.summary.typeErrors)
        highCVEs = ($currentResults.summary.highCVEs) - ($baseline.summary.highCVEs)
    }
} else {
    Write-Host "⚠️ No baseline found - only current metrics available" -ForegroundColor Yellow
    $deltas = @{ status = "no-baseline" }
}

# Enhanced results with comparison
$results = @{
    timestamp = $timestamp
    current = $currentResults.summary
    baseline = if ($baseline) { $baseline.summary } else { $null }
    deltas = $deltas
    improvements = @{
        eslintWarningsReduced = if ($deltas.eslintWarnings) { $deltas.eslintWarnings -lt 0 } else { $false }
        eslintErrorsReduced = if ($deltas.eslintErrors) { $deltas.eslintErrors -lt 0 } else { $false }
        typeErrorsReduced = if ($deltas.typeErrors) { $deltas.typeErrors -le 0 } else { $false }
        securityImproved = if ($deltas.highCVEs) { $deltas.highCVEs -le 0 } else { $false }
    }
}

# Save results
$results | ConvertTo-Json -Depth 10 | Out-File "$OutputDir/after-complete.json" -Encoding UTF8

# Generate comparison report
$comparisonMd = @"
# ODAVL After Evidence Report

**Generated**: $timestamp  
**Project**: $projectRoot

## Current Metrics

### ESLint Analysis
- **Warnings**: $($results.current.eslintWarnings)
- **Errors**: $($results.current.eslintErrors)

### TypeScript Analysis
- **Compilation Errors**: $($results.current.typeErrors)

### Security Analysis  
- **Status**: $($results.current.securityStatus)
- **High Severity CVEs**: $($results.current.highCVEs)

"@

if ($baseline) {
    $comparisonMd += @"

## Comparison with Baseline

### Changes (Delta)
- **ESLint Warnings**: $($deltas.eslintWarnings) ($(if($deltas.eslintWarnings -lt 0){"✅ Improved"}elseif($deltas.eslintWarnings -eq 0){"➖ No change"}else{"❌ Increased"}))
- **ESLint Errors**: $($deltas.eslintErrors) ($(if($deltas.eslintErrors -lt 0){"✅ Improved"}elseif($deltas.eslintErrors -eq 0){"➖ No change"}else{"❌ Increased"}))
- **TypeScript Errors**: $($deltas.typeErrors) ($(if($deltas.typeErrors -lt 0){"✅ Improved"}elseif($deltas.typeErrors -eq 0){"➖ No change"}else{"❌ Increased"}))
- **High CVEs**: $($deltas.highCVEs) ($(if($deltas.highCVEs -lt 0){"✅ Improved"}elseif($deltas.highCVEs -eq 0){"➖ No change"}else{"❌ Increased"}))

### Overall Assessment
$(if($results.improvements.eslintWarningsReduced -or $results.improvements.typeErrorsReduced){"✅ **SUCCESS**: Code quality improvements detected"}else{"⚠️ **REVIEW**: No significant improvements detected"})

"@
} else {
    $comparisonMd += "`n## Baseline Comparison`n*No baseline data available for comparison*`n"
}

$comparisonMd += @"

## Next Steps
1. Review delta analysis for any unexpected changes
2. Validate that improvements align with ODAVL goals  
3. Generate final success story report
4. Proceed with pilot expansion if results are positive

---
*Report generated by ODAVL Pilot Evidence Collection*
"@

$comparisonMd | Out-File "$OutputDir/comparison.md" -Encoding UTF8

if ($Json) {
    $results | ConvertTo-Json -Depth 5
} else {
    Write-Host ""
    Write-Host "📊 After Collection Complete" -ForegroundColor Green
    Write-Host "  📁 Reports saved to: $OutputDir"
    if ($deltas.eslintWarnings -ne $null) {
        Write-Host "  📋 ESLint Warnings: $($deltas.eslintWarnings) delta"
        Write-Host "  🔧 TypeScript Errors: $($deltas.typeErrors) delta"  
        Write-Host "  🔒 High CVEs: $($deltas.highCVEs) delta"
        if ($results.improvements.eslintWarningsReduced -or $results.improvements.typeErrorsReduced) {
            Write-Host "  ✅ Overall: Improvements detected!" -ForegroundColor Green
        }
    }
}

exit 0
