# .github/workflows/odavl.yml
name: ODAVL Insight

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ODAVL Insight Analysis
        uses: odavl-studio/insight-action@v1
        with:
          token: ${{ secrets.ODAVL_TOKEN }}
          quality-gates: true
          fail-on-error: true