import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { AuthService, validatePassword } from '@odavl-studio/auth';
import { createPrismaAdapter } from '@/lib/auth-adapter';
import { EmailService } from '@odavl-studio/email';
import crypto from 'crypto';
import { withValidation } from '@/lib/validation/middleware';
import { registerSchema } from '@/lib/validation/schemas';
import { withRateLimit, authLimiter } from '@/lib/rate-limit';

/**
 * POST /api/auth/register
 * Register a new user
 * Rate limited: 5 requests per 15 minutes
 */

export const POST = withRateLimit(
  authLimiter,
  withValidation(registerSchema, async (data, req) => {
  try {
    const { email, password, name } = data;

    // Validate password strength
    const passwordValidation = validatePassword(password);
    if (!passwordValidation.valid) {
      return NextResponse.json(
        { error: 'Password validation failed', details: passwordValidation.errors },
        { status: 400 }
      );
    }

    // Use AuthService for registration
    const adapter = createPrismaAdapter(prisma);
    const authService = new AuthService(adapter);

    const result = await authService.register({ email, password, name });
    const user = result.user;
    const tokens = { accessToken: result.accessToken, refreshToken: result.refreshToken };

    // Generate email verification token
    const verificationToken = crypto.randomBytes(32).toString('hex');
    
    // Update user with verification token
    await prisma.user.update({
      where: { id: user.id },
      data: {
        emailVerificationToken: verificationToken,
        emailVerified: false, // Ensure not verified yet
      },
    });

    // Send verification email (don't block registration if email fails)
    try {
      const emailService = new EmailService({
        host: process.env.SMTP_HOST || 'smtp.gmail.com',
        port: parseInt(process.env.SMTP_PORT || '587'),
        secure: false,
        auth: {
          user: process.env.SMTP_USER || '',
          pass: process.env.SMTP_PASSWORD || '',
        },
        from: {
          name: 'ODAVL Studio',
          email: process.env.SMTP_FROM || 'noreply@odavl.com',
        },
      });

      const baseUrl = process.env.NEXTAUTH_URL || 'http://localhost:3001';
      await emailService.sendVerificationEmail(
        user.email,
        user.name || 'User',
        verificationToken,
        baseUrl
      );
    } catch (emailError) {
      console.error('Failed to send verification email:', emailError);
      // Continue registration even if email fails
    }

    // Create FREE subscription for new user
    const oneMonthLater = new Date();
    oneMonthLater.setMonth(oneMonthLater.getMonth() + 1);

    await prisma.subscription.create({
      data: {
        userId: user.id,
        tier: 'FREE',
        status: 'active',
        maxProjects: 3,
        maxAnalysesPerMonth: 100,
        maxStorageGB: 1.0,
        currentPeriodStart: new Date(),
        currentPeriodEnd: oneMonthLater,
      },
    });

    // Store session (tokens already generated by AuthService)
    await prisma.session.create({
      data: {
        userId: user.id,
        token: tokens.accessToken,
        refreshToken: tokens.refreshToken,
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
      },
    });

    // Set cookies
    const response = NextResponse.json({
      message: 'Registration successful! Please check your email to verify your account.',
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
        emailVerified: false,
      },
      accessToken: tokens.accessToken,
    });

    response.cookies.set('accessToken', tokens.accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 15 * 60, // 15 minutes
    });

    response.cookies.set('refreshToken', tokens.refreshToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 7 * 24 * 60 * 60, // 7 days
    });

    return response;
  } catch (error) {
    console.error('Register error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
  })
);
